### PR TITLE
Fix missing semicolumn for task with no param or retval

### PR DESCRIPTION
**Pull request by djoffe**
Added the missing parentheses.

This PR resolves issue #1.

### CODE REVIEW

**Comment by mballance** [comment]
Many thanks, @djoffe! One small question, I think I'm overlooking the line in the diff that adds the missing semicolon. I see one line where you added an extra layer of parens. Really just want to be sure that the fix is really present. Can you point me to the specific line?

**Comment by mulianov** [comment]
@djoffe Line 418 fix this issue by adding proper (). Please merge it asap

**Comment by mballance** [comment]
Got it, thanks!

**Comment by djoffe** [comment]
Sorry @mballance, missed your reply!
Thanks for the merge :)

**Pull request merged**
